_protected/models/ProductoDistribuidor.php
<?php

namespace app\models;

use \app\models\base\ProductoDistribuidor as BaseProductoDistribuidor;

/**
 * This is the model class for table "producto_distribuidor".
 */
class ProductoDistribuidor extends BaseProductoDistribuidor
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return array_replace_recursive(parent::rules(),
	    [
            [['referencia', 'nombre', 'distribuidor_id'], 'required'],
            [['precio'], 'number'],
            [['distribuidor_id', 'created_by', 'updated_by'], 'integer'],
            [['fecha','created_at', 'updated_at'], 'safe'],
            [['codigo', 'marca'], 'string', 'max' => 45],
            [['referencia', 'nombre'], 'string', 'max' => 255]
        ]);
    }
	
}

_protected/controllers/ProductoDistribuidorController.php
<?php

namespace app\controllers;

use app\models\ProductoDistribuidor;
use app\models\ProductoDistribuidorSearch;
use kartik\mpdf\Pdf;
use PHPExcel;
use PHPExcel_IOFactory;
use PHPExcel_Style_Alignment;
use PHPExcel_Style_Border;
use PHPExcel_Style_Fill;
use Yii;
use yii\web\NotFoundHttpException;

/**
 * ProductoDistribuidorController implements the CRUD actions for ProductoDistribuidor model.
 */
class ProductoDistribuidorController extends AppController{

    /**
     * Lists all ProductoDistribuidor models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProductoDistribuidorSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    
    /**
     * Lists all ProductoDistribuidor models with comparative.
     * @return mixed
     */
    public function actionReport()
    {
        $searchModel = new ProductoDistribuidorSearch();
        $searchModel->distribuidor_id = 7;
       // $searchModel->precio = '>0' ;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $distribuidores = ProductoDistribuidor::getDistribuidores();
        $menores = ProductoDistribuidor::getMenores();
        return $this->render('report', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'distribuidores' => $distribuidores,
            'menores' => $menores,
        ]);
    }

    /**
     * Displays a single ProductoDistribuidor model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new ProductoDistribuidor model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ProductoDistribuidor();

        if ($model->loadAll(Yii::$app->request->post()) && $model->saveAll()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing ProductoDistribuidor model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->loadAll(Yii::$app->request->post()) && $model->saveAll()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing ProductoDistribuidor model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->deleteWithRelated();

        return $this->redirect(['index']);
    }
    
    /**
     * 
     * Export ProductoDistribuidor information into PDF format.
     * @param string $id
     * @return mixed
     */
    public function actionPdf($id) {
        $model = $this->findModel($id);

        $content = $this->renderAjax('_pdf', [
            'model' => $model,
        ]);

        $pdf = new Pdf([
            'mode' => Pdf::MODE_CORE,
            'format' => Pdf::FORMAT_A4,
            'orientation' => Pdf::ORIENT_PORTRAIT,
            'destination' => Pdf::DEST_BROWSER,
            'content' => $content,
            'cssFile' => '@vendor/kartik-v/yii2-mpdf/assets/kv-mpdf-bootstrap.min.css',
            'cssInline' => '.kv-heading-1{font-size:18px}',
            'options' => ['title' => Yii::$app->name],
            'methods' => [
                'SetHeader' => [Yii::$app->name],
                'SetFooter' => ['{PAGENO}'],
            ]
        ]);

        return $pdf->render();
    }

    
    /**
     * Finds the ProductoDistribuidor model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return ProductoDistribuidor the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ProductoDistribuidor::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
        }
    }
    
    /**
     * 
     * Export report information into Excel format.
     * @return mixed
     */
     /*
	EXPORT WITH PHPEXCEL
	*/ 
	public function actionExport()
    {
        ini_set('memory_limit', '1000M');
         $arrData = ProductoDistribuidor::find()->select("`producto_distribuidor`.*, distribuidor.`nombre` nomdist")
                        ->join('JOIN', 'distribuidor', '`distribuidor_id` = distribuidor.id')
                        ->asArray()->all();
            
        // Create new PHPExcel object
        $objPHPExcel = new PHPExcel();
        // Set document properties
        $objPHPExcel->getProperties()->setCreator("REYPAR - SICOM")
                                            ->setLastModifiedBy("REYPAR - SICOM")
                                            ->setTitle("Reporte competencia")
                                            ->setKeywords("office 2007 openxml php")
                                            ->setCategory("Result file");
        $objPHPExcel->setActiveSheetIndex(0)
                    ->setCellValue('A1', 'Referencia')
                    ->setCellValue('B1', 'Nombre')
                    ->setCellValue('C1', 'Precio')
                    ->setCellValue('D1', 'Marca')
                    ->setCellValue('E1', 'Distribuidor')
                    ->setCellValue('F1', 'Fecha');
  
        $objPHPExcel->getActiveSheet()->getStyle('A1:F1')->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle('A1:F1')->getFill()
                    ->setFillType(PHPExcel_Style_Fill::FILL_SOLID)
                    ->getStartColor()
                    ->setARGB('bcedb4');
        $objPHPExcel->getActiveSheet()->freezePane('A2');
        $objPHPExcel->getActiveSheet()->getStyle('A1:F1')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
        $objPHPExcel->getActiveSheet()->getStyle('A1:F1')->getBorders()->getAllBorders()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN);

        $baseRow=2;
        foreach($arrData as $producto){
            // Add some data
            $objPHPExcel->setActiveSheetIndex(0)
                        ->setCellValue('A'.$baseRow, $producto['referencia'])
                        ->setCellValue('B'.$baseRow, $producto['nombre'])
                        ->setCellValue('C'.$baseRow, number_format($producto['precio']))
                        ->setCellValue('D'.$baseRow, $producto['marca'])
                        ->setCellValue('E'.$baseRow, $producto['nomdist'])
                        ->setCellValue('F'.$baseRow, $producto['fecha']);
            $baseRow++;
        }
        
           
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment;filename="export.xlsx"');
        header('Cache-Control: max-age=0');
        $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, "Excel2007");
        $objWriter->save('php://output');
        exit();
    }   

}

_protected/views/producto-distribuidor/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ProductoDistribuidor */
/* @var $form yii\widgets\ActiveForm */

?>

<div class="producto-distribuidor-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->errorSummary($model); ?>

    <?= $form->field($model, 'id', ['template' => '{input}'])->textInput(['style' => 'display:none']); ?>

    <?= $form->field($model, 'referencia')->textInput(['maxlength' => true, 'placeholder' => 'Referencia']) ?>

    <?= $form->field($model, 'nombre')->textInput(['maxlength' => true, 'placeholder' => 'Nombre']) ?>

    <?= $form->field($model, 'precio')->textInput(['maxlength' => true, 'placeholder' => 'Precio']) ?>
    
    <?= $form->field($model, 'marca')->textInput(['maxlength' => true, 'placeholder' => 'Marca']) ?>

    <?= $form->field($model, 'distribuidor_id')->widget(\kartik\widgets\Select2::classname(), [
        'data' => \yii\helpers\ArrayHelper::map(\app\models\Distribuidor::find()->orderBy('id')->asArray()->all(), 'id', 'nombre'),
        'options' => ['placeholder' => Yii::t('app', 'Choose Distribuidor')],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]); ?>

     <?= $form->field($model, 'fecha')->widget(\kartik\datecontrol\DateControl::classname(), [ 
		       'type' => \kartik\datecontrol\DateControl::FORMAT_DATE, 
		       'saveFormat' => 'php:Y-m-d', 
		       'ajaxConversion' => true, 
		       'options' => [ 
		           'pluginOptions' => [ 
		               'placeholder' => Yii::t('app', 'Choose Fecha'), 
		               'autoclose' => true 
		           ],
                            'size' => 'sm'
		       ], 
		   ]); ?> 
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Cancel'), Yii::$app->request->referrer , ['class'=> 'btn btn-danger']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

_protected/views/producto-distribuidor/_pdf.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use kartik\grid\GridView;

/* @var $this yii\web\View */
/* @var $model app\models\ProductoDistribuidor */

$this->title = $model->nombre;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Producto Distribuidor'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="producto-distribuidor-view">

    <div class="row">
        <div class="col-sm-9">
            <h2><?= Yii::t('app', 'Producto Distribuidor').' '. Html::encode($this->title) ?></h2>
        </div>
    </div>

    <div class="row">
<?php 
    $gridColumn = [
        ['attribute' => 'id', 'visible' => false],
        'referencia',
        'nombre',
        'precio',
        'marca',
        [
                'attribute' => 'distribuidor.nombre',
                'label' => Yii::t('app', 'Distribuidor')
            ],
    ];
    echo DetailView::widget([
        'model' => $model,
        'attributes' => $gridColumn
    ]); 
?>
    </div>
</div>

_protected/views/producto-distribuidor/_script.php
<?php
use yii\helpers\Url;

?>
<script>
    function addRow<?= $class ?>() {
        var data = $('#add-<?= $relID?> :input').serializeArray();
        data.push({name: '_action', value : 'add'});
        $.ajax({
            type: 'POST',
            url: '<?php echo Url::to(['add-'.$relID]); ?>',
            data: data,
            success: function (data) {
                $('#add-<?= $relID?>').html(data);
            }
        });
    }
    function delRow<?= $class ?>(id) {
        $('#add-<?= $relID?> tr[data-key=' + id + ']').remove();
    }
</script>

_protected/views/producto-distribuidor/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ProductoDistribuidorSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="form-producto-distribuidor-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id', ['template' => '{input}'])->textInput(['style' => 'display:none']); ?>

    <?= $form->field($model, 'referencia')->textInput(['maxlength' => true, 'placeholder' => 'Referencia']) ?>

    <?= $form->field($model, 'nombre')->textInput(['maxlength' => true, 'placeholder' => 'Nombre']) ?>

    <?= $form->field($model, 'precio')->textInput(['maxlength' => true, 'placeholder' => 'Precio']) ?>

    <?php /* echo $form->field($model, 'marca')->textInput(['maxlength' => true, 'placeholder' => 'Marca']) */ ?>

    <?php /* echo $form->field($model, 'distribuidor_id')->widget(\kartik\widgets\Select2::classname(), [
        'data' => \yii\helpers\ArrayHelper::map(\app\models\Distribuidor::find()->orderBy('id')->asArray()->all(), 'id', 'nombre'),
        'options' => ['placeholder' => Yii::t('app', 'Choose Distribuidor')],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]); */ ?>
    <?php /* echo $form->field($model, 'fecha')->widget(\kartik\datecontrol\DateControl::classname(), [ 
		       'type' => \kartik\datecontrol\DateControl::FORMAT_DATE, 
		       'saveFormat' => 'php:Y-m-d', 
		       'ajaxConversion' => true, 
		       'options' => [ 
		           'pluginOptions' => [ 
		               'placeholder' => Yii::t('app', 'Choose Fecha'), 
		               'autoclose' => true 
		           ],
                           'size' => 'sm'
		       ], 
		   ]); */ ?> 
    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

_protected/views/producto-distribuidor/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\ProductoDistribuidor */

$this->title = Yii::t('app', 'Create Producto Distribuidor');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Producto Distribuidor'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="producto-distribuidor-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

_protected/views/producto-distribuidor/index.php
<?php

/* @var $this yii\web\View */
/* @var $searchModel app\models\ProductoDistribuidorSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

use yii\helpers\Html;
use kartik\export\ExportMenu;
use kartik\grid\GridView;

$this->title = Yii::t('app', 'Producto Distribuidor');
$this->params['breadcrumbs'][] = $this->title;
$search = "$('.search-button').click(function(){
	$('.search-form').toggle(1000);
	return false;
});";
$this->registerJs($search);
?>
<div class="producto-distribuidor-index">

    <h1><?= Html::encode($this->title) ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
    <span class="pull-right">
        <?php // Html::a(Yii::t('app', 'Create Producto Distribuidor'), ['create'], ['class' => 'btn btn-success']) ?>
          <?=
            Html::a('<i class="fa glyphicon glyphicon-export"></i> ' . Yii::t('app', 'Exportar todo'), ['producto-distribuidor/export'], ['class' => 'btn btn-primary',
                'title' => Yii::t('app', 'Exportar todo')])
            ?>
        <?php //echo Html::a(Yii::t('app', 'Advance Search'), '#', ['class' => 'btn btn-info search-button']) ?>
    </span>
    </h1>
    
    <div class="search-form" style="display:none">
        <?=  $this->render('_search', ['model' => $searchModel]); ?>
    </div>
    <?php ini_set('max_execution_time', 0);
    ini_set('memory_limit', '1000M');
    $gridColumn = [
        ['attribute' => 'id', 'visible' => false],
        'referencia',
        'nombre',
        [
        'attribute' => 'precio', 
        'value' => function($model) {
                return '$' . number_format($model->precio,0);   
            },
        'hAlign'=>'right'
        ],
        'marca',
        [
            'attribute' => 'distribuidor_id',
            'label' => Yii::t('app', 'Distribuidor'),
            'value' => function($model){
                return $model->distribuidor->nombre;
            },
            'filterType' => GridView::FILTER_SELECT2,
            'filter' => \yii\helpers\ArrayHelper::map(\app\models\Distribuidor::find()->asArray()->all(), 'id', 'nombre'),
            'filterWidgetOptions' => [
                'pluginOptions' => ['allowClear' => true],
            ],
            'filterInputOptions' => ['placeholder' => 'Distribuidor', 'id' => 'grid-producto-distribuidor-search-distribuidor_id']
        ],
        'updated_at',
        'distribuidor.fecha',
        [
            'class' => 'yii\grid\ActionColumn',
        ],
    ]; 
    ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => $gridColumn,
        'pjax' => true,
        'pjaxSettings' => ['options' => ['id' => 'kv-pjax-container-producto-distribuidor']],
        'panel' => [
            'type' => GridView::TYPE_PRIMARY,
            'heading' => '<span class="glyphicon glyphicon-book"></span>  ' . Html::encode($this->title),
        ],
        // your toolbar can include the additional full export menu
        'toolbar' => [
            '{export}',
            ExportMenu::widget([
                'dataProvider' => $dataProvider,
                'columns' => $gridColumn,
                'target' => ExportMenu::TARGET_BLANK,
                'showConfirmAlert' => false,
                'fontAwesome' => true,
                'stream' => false, // this will automatically save the file to a folder on web server
                'streamAfterSave' => true, // this will stream the file to browser after its saved on the web folder 
                'deleteAfterSave' => true, // this will delete the saved web file after it is streamed to browser,
                'batchSize' => 100,
  
                'dropdownOptions' => [
                    'label' => 'Todo',
                    'class' => 'btn btn-default',
                    'itemsBefore' => [
                        '<li class="dropdown-header">Exportar todo lo filtrado</li>',
                    ],
                ],
            ]) ,
        ],
    ]); ?>

</div>

_protected/views/producto-distribuidor/report.php
<?php
/* @var $this yii\web\View */
/* @var $searchModel app\models\ProductoDistribuidorSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

use yii\helpers\Html;
use kartik\grid\GridView;

$this->title = Yii::t('app', 'Producto Distribuidor');
$this->params['breadcrumbs'][] = $this->title;
$search = "$('.search-button').click(function(){
	$('.search-form').toggle(1000);
	return false;
});";
?>
<div class="producto-distribuidor-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]);  ?>

  
    <div class="search-form" style="display:none">
        <?= $this->render('_search', ['model' => $searchModel]); ?>
    </div>
    <?php
    $gridColumn = [
        'codigo',
        'referencia',
        'nombre',
        'marca',
        [   
        //    'label' => ' Precio'.($->distribuidor->descuento?' - '.$model->distribuidor->descuento.'%':''),
            'attribute' => 'precio',
            'format' => 'raw',
            'value' => function($model) use($menores){
                $precio = $model->precio == 0?  number_format($model->precio2,0).'*':number_format($model->precio,0);
                $bold = in_array($model->id, $menores)?'<b>':'';
                return $bold .'$' . $precio;
            },
        ],
    ];
    $arrDistribuidores = array();
    foreach ($distribuidores as $distribuidor) {
        $arrDistribuidores[] = [
            'label' => $distribuidor->nombre.' '.$distribuidor->fecha,
            'format' => 'raw',
            'value' => function($model) use ($distribuidor,$menores) {
                $str = '';
                $str = '<table><tbody>';
                $arrDistInfo = array();
                foreach ($model->productosDistribuidor as $producto) {
                    if ($distribuidor->distribuidor_id == $producto->distribuidor_id 
                            && (empty($arrDistInfo) || (array_search($producto->referencia, $arrDistInfo) === FALSE ))){
                        $bold = in_array($producto->id, $menores)?'<b>':'';
                        $str .= '<tr><td>' . $bold . $producto->referencia . '</td></tr>';
                        $arrDistInfo[] = $producto->referencia;
                    }
                }
                $str .= '</tbody></table>';
                return $str;
            }
        ];
        $arrDistribuidores[] = [
            'label' => ' Precio'.($distribuidor->descuento?' - '.$distribuidor->descuento.'%':''),
            'format' => 'raw',
            'value' => function($model) use ($distribuidor,$menores) {
                $str = '';
                $str = '<table><tbody>';
                $arrDistInfo = array();
                foreach ($model->productosDistribuidor as $producto) {
                    if ($distribuidor->distribuidor_id == $producto->distribuidor_id 
                            && (empty($arrDistInfo) || (array_search($producto->referencia, $arrDistInfo) === FALSE ))){
                        $bold = in_array($producto->id, $menores)?'<b>':'';
                        $str .= '<tr><td>$' . $bold . number_format($producto->precio, 0) . '</td></tr>';
                        $arrDistInfo[] = $producto->referencia;
                    }
                }
                $str .= '</tbody></table>';
                return $str;
            }
        ];
        $arrDistribuidores[] = [
            'label' => ' marca',
            'format' => 'raw',
            'value' => function($model) use ($distribuidor,$menores) {
                $str = '';
                $str = '<table><tbody>';
                $arrDistInfo = array();
                foreach ($model->productosDistribuidor as $producto) {
                    if ($distribuidor->distribuidor_id == $producto->distribuidor_id 
                            && (empty($arrDistInfo) || (array_search($producto->referencia, $arrDistInfo) === FALSE ))){
                        $bold = in_array($producto->id, $menores)?'<b>':'';
                        $str .= '<tr><td>' . $bold . $producto->marca . '</td></tr>';
                        $arrDistInfo[] = $producto->referencia;
                    }
                }
                $str .= '</tbody></table>';
                return $str;
            }
        ];
    }
    $gridColumn = array_merge($gridColumn, $arrDistribuidores);


//        [
//                'attribute' => 'distribuidor_id',
//                'label' => Yii::t('app', 'Distribuidor'),
//                'value' => function($model){
//                    return $model->distribuidor->nombre;
//                },
//                'filterType' => GridView::FILTER_SELECT2,
//                'filter' => \yii\helpers\ArrayHelper::map(\app\models\Distribuidor::find()->asArray()->all(), 'id', 'nombre'),
//                'filterWidgetOptions' => [
//                    'pluginOptions' => ['allowClear' => true],
//                ],
//                'filterInputOptions' => ['placeholder' => 'Distribuidor', 'id' => 'grid-producto-distribuidor-search-distribuidor_id']
//            ],
    $gridColumn[] = ['class' => 'yii\grid\ActionColumn'];
//    ]; 
    ?>
    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'autoXlFormat' => true,
//        'floatHeader'=>true,
//        'floatHeaderOptions'=>['scrollingTop'=>'50'],
        'export' => [
            'fontAwesome' => true,
            'showConfirmAlert' => false,
            'target' => GridView::TARGET_BLANK
        ],
        'filterModel' => $searchModel,
        'columns' => $gridColumn,
        'pjax' => true,
        'pjaxSettings' => ['options' => ['id' => 'kv-pjax-container-producto-distribuidor']],
        'panel' => [
            'type' => GridView::TYPE_PRIMARY,
            'heading' => '<span class="glyphicon glyphicon-book"></span>  ' . Html::encode($this->title),
        ],
            // your toolbar can include the additional full export menu
//        'toolbar' => [
//            '{export}',
//            ExportMenu::widget([
//                'dataProvider' => $dataProvider,
//                'columns' => $gridColumn,
//                'target' => ExportMenu::TARGET_BLANK,
//                'fontAwesome' => true,
//                'dropdownOptions' => [
//                    'label' => 'Full',
//                    'class' => 'btn btn-default',
//                    'itemsBefore' => [
//                        '<li class="dropdown-header">Export All Data</li>',
//                    ],
//                ],
//            ]),
//        ],
    ]);
    ?>
  <p>
        * Producto agotado
    </p>
</div>

_protected/views/producto-distribuidor/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\ProductoDistribuidor */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Producto Distribuidor',
]) . ' ' . $model->nombre;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Producto Distribuidor'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->nombre, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="producto-distribuidor-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

_protected/views/producto-distribuidor/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use kartik\grid\GridView;

/* @var $this yii\web\View */
/* @var $model app\models\ProductoDistribuidor */

$this->title = $model->nombre;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Producto Distribuidor'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<?php if (Yii::$app->session->hasFlash('success')): ?>
  <div class="alert alert-success alert-dismissable">
  <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
  <h4><i class="icon fa fa-check"></i>Saved!</h4>
  <?= Yii::$app->session->getFlash('success') ?>
  </div>
<?php endif; ?>

<div class="producto-distribuidor-view">

    <div class="row">
        <div class="col-sm-9">
            <h2><?= Yii::t('app', 'Producto Distribuidor').' '. Html::encode($this->title) ?></h2>
        </div>
        <div class="col-sm-3" style="margin-top: 15px">
<?=             
             Html::a('<i class="fa glyphicon glyphicon-hand-up"></i> ' . Yii::t('app', 'PDF'), 
                ['pdf', 'id' => $model->id],
                [
                    'class' => 'btn btn-danger',
                    'target' => '_blank',
                    'data-toggle' => 'tooltip',
                    'title' => Yii::t('app', 'Will open the generated PDF file in a new window')
                ]
            )?>
            
            <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
            <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                    'method' => 'post',
                ],
            ])
            ?>
        </div>
    </div>

    <div class="row">
<?php 
    $gridColumn = [
        ['attribute' => 'id', 'visible' => false],
        'referencia',
        'nombre',
        [
            'attribute' => 'precio',
            'value' =>  '$' . number_format($model->precio, 0)
        ],
        'marca',
        [
            'attribute' => 'distribuidor.nombre',
            'label' => Yii::t('app', 'Distribuidor'),
        ],
        'fecha',
    ];
    echo DetailView::widget([
        'model' => $model,
        'attributes' => $gridColumn
    ]); 
?>
    </div>
</div>