_protected/models/Distribuidor.php
<?php

namespace app\models;

use \app\models\base\Distribuidor as BaseDistribuidor;

/**
 * This is the model class for table "distribuidor".
 */
class Distribuidor extends BaseDistribuidor
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return array_replace_recursive(parent::rules(),
	    [
            [['nombre', 'columna_referencia', 'columna_precio', 'columna_nombre'], 'required'],
            [['created_at', 'updated_at'], 'safe'],
            [['descuento', 'created_by', 'updated_by'], 'integer'],
            [['nombre'], 'string', 'max' => 255],
            [['columna_referencia', 'columna_codigo', 'columna_precio', 'columna_nombre', 'columna_marca'], 'string', 'max' => 45]
        ]);
    }
	
}

_protected/controllers/DistribuidorController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Distribuidor;
use app\models\DistribuidorSearch;
use app\models\ProductoDistribuidor;
use app\models\Producto;
use yii\web\NotFoundHttpException;
use app\models\UploadForm;
use yii\web\UploadedFile;

/**
 * DistribuidorController implements the CRUD actions for Distribuidor model.
 */
class DistribuidorController extends AppController {

    /**
     * Lists all Distribuidor models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new DistribuidorSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Distribuidor model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id) {
        $searchModel = new \app\models\ProductoDistribuidorSearch();
        $dataProvider = $searchModel->search(['ProductoDistribuidorSearch' => ['distribuidor_id' => $id]]);
        $model = $this->findModel($id);
//        $providerProducto = new \yii\data\ArrayDataProvider([
//            'allModels' => $model->productosDistribuidor,
//        ]);
        return $this->render('view', [
                    'model' => $this->findModel($id),
                    'providerProducto' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Distribuidor model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new Distribuidor();

        if ($model->loadAll(Yii::$app->request->post()) && $model->saveAll()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Distribuidor model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->loadAll(Yii::$app->request->post(), ['productosDistribuidor']) && $model->saveAll(['productosDistribuidor'])) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Imports a excel file.
     * @param integer $id
     * @return mixed
     * @author Juan Velez <juanfv@gmail.com>
     */
    public function actionImport($id) {
        $modelUpload = new UploadForm();

        ini_set('max_execution_time', 0);

        if (Yii::$app->request->isPost) {


            $modelUpload->file = UploadedFile::getInstance($modelUpload, 'file');
            $modelUpload->fecha = Yii::$app->request->post('UploadForm')['fecha'];
            $modelUpload->tipo = 'na';

            if ($modelUpload->upload()) {
//                $model = Distribuidor::findOne($_GET["id"]);
                if (($this->findModel($_GET["id"]))) {
                    $model = $this->findModel($_GET["id"]);
                    $result = $this->loadFile($modelUpload, $model);
                    Yii::$app->getSession()->setFlash('success', $result);
                    return $this->redirect(['view', 'id' => $model->id]);
                } else {
                    echo "<pre>";
                    echo "Distribuidor no encontrado";
                    echo "</pre>";
                    die;
                }
            }
        }

        return $this->render('import', ['model' => $modelUpload]);
    }

    /**
     * 
     * @author Juan Velez <juanfv@gmail.com>
     */
    public function loadFile($modelUpload, $model) {
        $inputFiles = 'uploads/' . $modelUpload->file->baseName . '.' . $modelUpload->file->extension;
        $workbook = \Akeneo\Component\SpreadsheetParser\SpreadsheetParser::open($inputFiles);
        $worsheets = $workbook->getWorksheets();
        $alphabet = array('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
            'aa', 'ab', 'ac', 'ad', 'ae', 'af', 'ag', 'ah', 'ai', 'aj', 'ak', 'al', 'am', 'an', 'ao', 'ap', 'aq', 'ar', 'as', 'at', 'au', 'av', 'aw', 'ax', 'ay', 'az',);
        $columna_nombre = array_search(strtolower($model->columna_nombre), $alphabet);
        $columna_referencia = array_search(strtolower($model->columna_referencia), $alphabet);
        $columna_precio = array_search(strtolower($model->columna_precio), $alphabet);
        $columna_marca = array_search(strtolower($model->columna_marca), $alphabet);
        $fecha = $modelUpload->fecha;
        $created_by = Yii::$app->user->id;
        $updated_by = Yii::$app->user->id;
        $created_at = new \yii\db\Expression('NOW()');
        $updated_at = new \yii\db\Expression('NOW()');
        $arrProductos = array();
        $arrDistInfo = array();
        //controla que no se ingresen referencias repetidas
        foreach ($worsheets as $sheet) {
            $myWorksheetIndex = $workbook->getWorksheetIndex($sheet);
            foreach ($workbook->createRowIterator($myWorksheetIndex) as $rowIndex => $row) {
                $nombre = trim(isset($row[$columna_nombre]) && (is_string($row[$columna_nombre]) || is_numeric($row[$columna_nombre])) ? $row[$columna_nombre] : '');
                $referencia = trim(isset($row[$columna_referencia]) && (is_string($row[$columna_referencia]) || is_numeric($row[$columna_referencia])) ? $row[$columna_referencia] : '');
                $precio = trim(isset($row[$columna_precio]) && is_numeric($row[$columna_precio]) ? $row[$columna_precio] : '');
                $precio = $model->descuento ? @intval($precio - ($precio * ($model->descuento / 100))) : $precio;
                $marca = trim(isset($row[$columna_marca]) && (is_string($row[$columna_marca]) || is_numeric($row[$columna_marca])) ? $row[$columna_marca] : '');
                $i = floor($rowIndex / 500);
                if ($nombre != '' && $referencia != '' && is_numeric($precio) && array_search($referencia, $arrDistInfo) === FALSE) {
                    $arrProductos[$i][] = [$referencia, $nombre, $precio, $marca, 1, 1, $model->id, $updated_at, $updated_by, $created_at, $created_by];
                    $arrDistInfo[] = $referencia;
                }
            }
        }
        $deletedRows = 0;
        $updatedRows = 0;
        if (!empty($arrProductos)) {
//            ini_set('innodb_lock_wait_timeout', '5000');
            // inserta productos en la tabla
            foreach ($arrProductos as $productos) {
                Producto::batchUpdate('producto_distribuidor',
                        ['referencia', 'nombre', 'precio', 'marca', 'nuevo', 'viejo', 'distribuidor_id', 'updated_at', 'updated_by', 'created_at', 'created_by'],
                        $productos,
                        ['nombre', 'precio', 'viejo', 'updated_at', 'updated_by'])->execute();
            }
            //elimina productos que ya no aparecen
//            $deletedRows = ProductoDistribuidor::deleteAll('nuevo IS NULL AND viejo IS NULL AND distribuidor_id = :id', ['id' => $model->id]);

            // Actualiza el código en los registros nuevos
            Distribuidor::updateAll(['fecha' => $fecha], ['id' => $model->id]);
            $updatedRows = ProductoDistribuidor::updateProductoDistribuidor($model->id);


            ProductoDistribuidor::updateAll(['nuevo' => '', 'viejo' => ''], 'nuevo = 1 OR viejo = 1');
        }

        //   $deletedFile = unlink($inputFiles);
        return "Proceso tenminado";
//        return  "Registros borrados: $deletedRows, Registros actualizados: $updatedRows";
    }

    /**
     * Deletes an existing Distribuidor model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id) {
        $this->findModel($id)->deleteWithRelated();
        return $this->redirect(['index']);
    }

    /**
     * 
     * Export Distribuidor information into PDF format.
     * @param integer $id
     * @return mixed
     */
    public function actionPdf($id) {
        $model = $this->findModel($id);
        $providerProducto = new \yii\data\ArrayDataProvider([
            'allModels' => $model->productos,
        ]);

        $content = $this->renderAjax('_pdf', [
            'model' => $model,
            'providerProducto' => $providerProducto,
        ]);

        $pdf = new \kartik\mpdf\Pdf([
            'mode' => \kartik\mpdf\Pdf::MODE_CORE,
            'format' => \kartik\mpdf\Pdf::FORMAT_A4,
            'orientation' => \kartik\mpdf\Pdf::ORIENT_PORTRAIT,
            'destination' => \kartik\mpdf\Pdf::DEST_BROWSER,
            'content' => $content,
            'cssFile' => '@vendor/kartik-v/yii2-mpdf/assets/kv-mpdf-bootstrap.min.css',
            'cssInline' => '.kv-heading-1{font-size:18px}',
            'options' => ['title' => \Yii::$app->name],
            'methods' => [
                'SetHeader' => [\Yii::$app->name],
                'SetFooter' => ['{PAGENO}'],
            ]
        ]);

        return $pdf->render();
    }

    /**
     * Finds the Distribuidor model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Distribuidor the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Distribuidor::findOne($id)) !== null) {
            return $model;
        } else {

_protected/views/distribuidor/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Distribuidor */
/* @var $form yii\widgets\ActiveForm */

\mootensai\components\JsBlock::widget(['viewFile' => '_script', 'pos'=> \yii\web\View::POS_END, 
    'viewParams' => [
        'class' => 'Producto', 
        'relID' => 'producto', 
        'value' => \yii\helpers\Json::encode($model->productosDistribuidor),
        'isNewRecord' => ($model->isNewRecord) ? 1 : 0
    ]
]);
?>

<div class="distribuidor-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->errorSummary($model); ?>

    <?= $form->field($model, 'id', ['template' => '{input}'])->textInput(['style' => 'display:none']); ?>

    <?= $form->field($model, 'nombre')->textInput(['maxlength' => true, 'placeholder' => 'Nombre']) ?>

    <?= $form->field($model, 'columna_referencia')->textInput(['maxlength' => true, 'placeholder' => 'Columna Referencia']) ?>

    <?= $form->field($model, 'columna_precio')->textInput(['maxlength' => true, 'placeholder' => 'Columna Precio']) ?>
    
    <?= $form->field($model, 'columna_nombre')->textInput(['maxlength' => true, 'placeholder' => 'Columna Nombre']) ?>

    <?= $form->field($model, 'columna_marca')->textInput(['maxlength' => true, 'placeholder' => 'Columna Marca']) ?>
    
    <?= $form->field($model, 'descuento')->textInput(['placeholder' => 'Descuento']) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Cancel'), Yii::$app->request->referrer , ['class'=> 'btn btn-danger']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

_protected/views/distribuidor/_formProductoDistribuidor.php
<div class="form-group" id="add-producto-distribuidor">
<?php
use kartik\grid\GridView;
use kartik\builder\TabularForm;
use yii\data\ArrayDataProvider;
use yii\helpers\Html;
use yii\widgets\Pjax;

$dataProvider = new ArrayDataProvider([
    'allModels' => $row,
    'pagination' => [
        'pageSize' => -1
    ]
]);
echo TabularForm::widget([
    'dataProvider' => $dataProvider,
    'formName' => 'ProductoDistribuidor',
    'checkboxColumn' => false,
    'actionColumn' => false,
    'attributeDefaults' => [
        'type' => TabularForm::INPUT_TEXT,
    ],
    'attributes' => [
        "id" => ['type' => TabularForm::INPUT_HIDDEN, 'visible' => false],
        'referencia' => ['type' => TabularForm::INPUT_TEXT],
        'nombre' => ['type' => TabularForm::INPUT_TEXT],
        'precio' => ['type' => TabularForm::INPUT_TEXT],
        'marca' => ['type' => TabularForm::INPUT_TEXT],
        'fecha' => ['type' => TabularForm::INPUT_WIDGET,
            'widgetClass' => \kartik\datecontrol\DateControl::classname(),
            'options' => [
                'type' => \kartik\datecontrol\DateControl::FORMAT_DATE,
                'saveFormat' => 'php:Y-m-d',
                'ajaxConversion' => true,
                'options' => [
                    'pluginOptions' => [
                        'placeholder' => Yii::t('app', 'Choose Fecha'),
                        'autoclose' => true
                    ],
                    'size' => 'sm'
                ],
            ]
        ],
        'del' => [
            'type' => 'raw',
            'label' => '',
            'value' => function($model, $key) {
                return Html::a('<i class="glyphicon glyphicon-trash"></i>', '#', ['title' =>  Yii::t('app', 'Delete'), 'onClick' => 'delRowProductoDistribuidor(' . $key . '); return false;', 'id' => 'producto-distribuidor-del-btn']);
            },
        ],
    ],
    'gridSettings' => [
        'panel' => [
            'heading' => false,
            'type' => GridView::TYPE_DEFAULT,
            'before' => false,
            'footer' => false,
            'after' => Html::button('<i class="glyphicon glyphicon-plus"></i>' . Yii::t('app', 'Add Producto Distribuidor'), ['type' => 'button', 'class' => 'btn btn-success kv-batch-create', 'onClick' => 'addRowProductoDistribuidor()']),
        ]
    ]
]);
echo  "    </div>\n\n";
?>

_protected/views/distribuidor/_pdf.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use kartik\grid\GridView;

/* @var $this yii\web\View */
/* @var $model app\models\Distribuidor */

$this->title = $model->nombre;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Distribuidor'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="distribuidor-view">

    <div class="row">
        <div class="col-sm-9">
            <h2><?= Yii::t('app', 'Distribuidor').' '. Html::encode($this->title) ?></h2>
        </div>
    </div>

    <div class="row">
<?php 
    $gridColumn = [
        ['attribute' => 'id', 'visible' => false],
        'nombre',
        'columna_referencia',
        'columna_precio',
        'columna_nombre',
        'columna_marca',
    ];
    echo DetailView::widget([
        'model' => $model,
        'attributes' => $gridColumn
    ]); 
?>
    </div>
    
    <div class="row">
<?php
if($providerProducto->totalCount){
    $gridColumnProducto = [
        ['class' => 'yii\grid\SerialColumn'],
        ['attribute' => 'id', 'visible' => false],
        'referencia',
        'nombre',
        'precio1',
        'precio2',
        'precio4',
        'existencia',
        'ctoprm',
        'upcompra',
        'ufcompra',
        'ufvta',
        [
                'attribute' => 'proveedor.nombre',
                'label' => Yii::t('app', 'Proveedor')
            ],
        'nombre_proveedor',
            ];
    echo Gridview::widget([
        'dataProvider' => $providerProducto,
        'panel' => [
            'type' => GridView::TYPE_PRIMARY,
            'heading' => Html::encode(Yii::t('app', 'Producto')),
        ],
        'panelHeadingTemplate' => '<h4>{heading}</h4>{summary}',
        'toggleData' => false,
        'columns' => $gridColumnProducto
    ]);
}
?>
    </div>
</div>

_protected/views/distribuidor/_script.php
<?php
use yii\helpers\Url;

?>
<script>
    function addRow<?= $class ?>() {
        var data = $('#add-<?= $relID?> :input').serializeArray();
        data.push({name: '_action', value : 'add'});
        $.ajax({
            type: 'POST',
            url: '<?php echo Url::to(['add-'.$relID]); ?>',
            data: data,
            success: function (data) {
                $('#add-<?= $relID?>').html(data);
            }
        });
    }
    function delRow<?= $class ?>(id) {
        $('#add-<?= $relID?> tr[data-key=' + id + ']').remove();
    }
</script>

_protected/views/distribuidor/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\DistribuidorSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="form-distribuidor-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id', ['template' => '{input}'])->textInput(['style' => 'display:none']); ?>

    <?= $form->field($model, 'nombre')->textInput(['maxlength' => true, 'placeholder' => 'Nombre']) ?>

    <?= $form->field($model, 'columna_referencia')->textInput(['maxlength' => true, 'placeholder' => 'Columna Referencia']) ?>

    <?= $form->field($model, 'columna_precio')->textInput(['maxlength' => true, 'placeholder' => 'Columna Precio']) ?>

    <?php /* echo $form->field($model, 'columna_nombre')->textInput(['maxlength' => true, 'placeholder' => 'Columna Nombre']) */ ?>

    <?php /* echo $form->field($model, 'columna_marca')->textInput(['maxlength' => true, 'placeholder' => 'Columna Marca']) */ ?>

    <?php /* echo $form->field($model, 'descuento')->textInput(['placeholder' => 'Descuento']) */ ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

_protected/views/distribuidor/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Distribuidor */

$this->title = Yii::t('app', 'Create Distribuidor');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Distribuidor'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="distribuidor-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

_protected/views/distribuidor/import.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
?>

<div class="distribuidor-form">

<?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]) ?>

    <?= $form->field($model, 'fecha')->widget(\kartik\datecontrol\DateControl::classname(), [ 
                        'type' => \kartik\datecontrol\DateControl::FORMAT_DATE, 
                        'saveFormat' => 'php:Y-m-d', 
                        'ajaxConversion' => true, 
                        'widgetOptions' => [ 
                            'pluginOptions' => [ 
                                'placeholder' => Yii::t('app', 'Choose Fecha'), 
                                'autoclose' => true,
                                'todayHighlight' => true,
		           ],
                           'size' => 'sm'
		       ], 
		   ]); ?> 
    
<!--    'date' => ['type' => Form::INPUT_WIDGET, 
                        'widgetClass' => '\kartik\widgets\DatePicker',
                        'options' => ['pluginOptions' => ['format' => 'yyyy-mm-dd', 'autoclose'=>true, 'todayHighlight' => true]]],-->
    <?= $form->field($model, 'file')->fileInput() ?>

    <button>Importar</button>
    <br>
    <br>

    <div class="form-group">
        <?= Html::a(Yii::t('app', 'Cancel'), Yii::$app->request->referrer , ['class'=> 'btn btn-danger']) ?>
    </div>
<?php ActiveForm::end() ?>
</div>

_protected/views/distribuidor/index.php
<?php

/* @var $this yii\web\View */
/* @var $searchModel app\models\DistribuidorSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

use yii\helpers\Html;
use kartik\export\ExportMenu;
use kartik\grid\GridView;
use yii\helpers\Url;

$this->title = Yii::t('app', 'Distribuidor');
$this->params['breadcrumbs'][] = $this->title;
$search = "$('.search-button').click(function(){
	$('.search-form').toggle(1000);
	return false;
});";
$this->registerJs($search);
?>
<div class="distribuidor-index">

    <h1><?= Html::encode($this->title) ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
    <span class="pull-right">
        <?= Html::a(Yii::t('app', 'Create Distribuidor'), ['create'], ['class' => 'btn btn-success']) ?>
    </span>
    </h1>
    <?php 
    $gridColumn = [
        ['attribute' => 'id', 'visible' => false],
        'nombre',
        'columna_referencia',
        'columna_precio',
        'columna_nombre',
        'columna_marca',
        'descuento',
        'fecha',
        [ 
            'class' => 'yii\grid\ActionColumn',
            'template' => '{view} {update} {delete} {import}',
            'buttons' => ['view' => function ($url, $model) {
                            $url = Url::to(['distribuidor/view', 'id' =>  $model->id]);
                            return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, ['title' => Yii::t('yii', 'View')]);
                        },
                        'update' => function ($url, $model) {
                            $url = Url::to(['distribuidor/update', 'id' =>  $model->id]);
                            return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, ['title' => Yii::t('yii', 'Update')]);
                        },
                        'delete' => function ($url, $model) {
                            $url = Url::to(['distribuidor/delete', 'id' =>  $model->id]);
                            return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, ['title' => Yii::t('yii', 'Delete'),
                                                                                                    'data-confirm' => Yii::t('yii', 'Are you sure you want to delete this item?'),
                                                                                                    'data-method' => 'post',
                            ]);
                        },
                        'import' => function ($url, $model) {
                            $url = Url::to(['distribuidor/import', 'id' =>  $model->id]);
                            return Html::a('<span class="glyphicon glyphicon-upload"></span>', $url, ['title' => Yii::t('yii', 'Import')]);
                        }
                        ],
                        
                                
        ],
    ]; 
    ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => $gridColumn,
        'pjax' => true,
        'pjaxSettings' => ['options' => ['id' => 'kv-pjax-container-distribuidor']],
        'panel' => [
            'type' => GridView::TYPE_PRIMARY,
            'heading' => '<span class="glyphicon glyphicon-th-large"></span>  ' . Html::encode($this->title),
        ],
        // your toolbar can include the additional full export menu
        'toolbar' => [
            '{export}',
            ExportMenu::widget([
                'dataProvider' => $dataProvider,
                'columns' => $gridColumn,
                'target' => ExportMenu::TARGET_BLANK,
                'fontAwesome' => true,
                'dropdownOptions' => [
                    'label' => 'Full',
                    'class' => 'btn btn-default',
                    'itemsBefore' => [
                        '<li class="dropdown-header">Export All Data</li>',
                    ],
                ],
            ]) ,
        ],
    ]); ?>

</div>

_protected/views/distribuidor/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Distribuidor */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Distribuidor',
]) . ' ' . $model->nombre;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Distribuidor'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->nombre, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="distribuidor-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

_protected/views/distribuidor/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use kartik\grid\GridView;

/* @var $this yii\web\View */
/* @var $model app\models\Distribuidor */

$this->title = $model->nombre;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Distribuidor'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="distribuidor-view">

    <div class="row">
        <div class="col-sm-9">
            <h2><?= Yii::t('app', 'Distribuidor').' '. Html::encode($this->title) ?></h2>
        </div>
        <div class="col-sm-3" style="margin-top: 15px">
            <?= Html::a('<i class="fa glyphicon glyphicon-upload"></i> ' .Yii::t('app', 'Import'),
                ['distribuidor/import', 'id' => $model->id],
                ['class' => 'btn btn-primary',
                    'title' => Yii::t('app', 'Import')]) ?>
            <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
            <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                    'method' => 'post',
                ],
            ])
            ?>
        </div>
    </div>

    <div class="row">
<?php 
    $gridColumn = [
        ['attribute' => 'id', 'visible' => false],
        'nombre',
        'columna_referencia',
        'columna_precio',
        'columna_nombre',
        'columna_marca',
        'descuento',
    ];
    echo DetailView::widget([
        'model' => $model,
        'attributes' => $gridColumn
    ]); 
?>
    </div>
    
    <div class="row">
<?php
if($providerProducto->totalCount){
    $gridColumnProducto = [
        ['class' => 'yii\grid\SerialColumn'],
            ['attribute' => 'id', 'visible' => false],
            'referencia',
            'nombre',
            [
                'attribute' => 'precio',
                'value' => function($model) {
                    return '$' . number_format($model->precio, 0);
                },
            ],
            'marca',
    ];
    echo Gridview::widget([
        'dataProvider' => $providerProducto,
        'pjax' => true,
        'pjaxSettings' => ['options' => ['id' => 'kv-pjax-container-producto']],
        'panel' => [
            'type' => GridView::TYPE_PRIMARY,
            'heading' => '<span class="glyphicon glyphicon-book"></span> ' . Html::encode(Yii::t('app', 'Producto')),
        ],
        'columns' => $gridColumnProducto
    ]);
}
?>
    </div>
</div>